### ISSUE TITLE
Settings object is missing "axis" property

### ISSUE THREAD

**Issue by creeve** [viktorlarsson/vue-tiny-slider#13]
Self explanatory.

**Comment by viktorlarsson** [comment]
I am a bit unsure on what you mean, there is an axis (which has a horizontal and vertical setting)?

**Comment by creeve** [comment]
Sorry, I meant the settings object on line 176.  "axis" is not set there like all the rest.

**Comment by MickCoelho** [comment]
Also, I noticed that when setting the object properly (as previously said on line 176), the `tiny-slider` doesn't set a fixed height for the `tns-inner tns-ovh` div.

**Comment by MickCoelho** [comment]
After investigating that `height` issue, it seems like it's something due to the orginal `tiny-slider` library. 
Changing [this line](https://github.com/ganlanyuan/tiny-slider/blob/master/src/tiny-slider.js#L2183) to
`innerWrapper.style.height = slideOffsetTops[Number(index + items)] - slideOffsetTops[index] + 'px';`
